#!/usr/bin/env python3
"""EDHOC Initiator + OSCORE client for the ZBook usb_ncm_net oscore build.

Drives the RFC 9668 sequential flow against the device Responder:
  1. Runs EDHOC (RFC 9528, method 3 static-DH, suite 2 P-256) to
     coap://<host>/.well-known/edhoc, using aiocoap's built-in initiator.
  2. Derives the OSCORE (RFC 8613) context and sends OSCORE-protected
     GET /hello, GET /led, PUT /led -- printing the decrypted replies.

aiocoap runs the handshake transparently on the first request to a URI that has
edhoc-oscore credentials registered. Key material comes from edhoc_creds.json
(generated by edhoc_keys.py; must match the flashed firmware's edhoc_creds.h).

Prereqs: scripts/.venv (see requirements.txt); the board flashed with the oscore
build; and the host USB-NCM interface set to 192.0.2.2/24 (see README).

    scripts/.venv/bin/python scripts/edhoc_oscore_client.py     # default host 192.0.2.1
"""
import argparse
import asyncio
import json
import pathlib

import cbor2

import aiocoap
from aiocoap.numbers.constants import TransportTuning

# The device runs a software P-256 EDHOC handshake with no ECC acceleration:
# composing message_2 (ephemeral keygen + two ECDH + point decompression) takes
# ~4 s on the RP2350, and message_3 processing adds more. aiocoap's default 2 s
# CoAP ACK timeout would retransmit message_1 long before message_2 arrives, and
# the responder regenerates its ephemeral key on every message_1 it sees -- so a
# retransmit silently derails the handshake and the client times out. Widen the
# ACK timeout well past the device's per-message compute time (patched on the
# TransportTuning class so aiocoap's *internal* EDHOC wire requests inherit it,
# not just the application requests) and cut the retransmit count.
TransportTuning.ACK_TIMEOUT = 12.0
TransportTuning.MAX_RETRANSMIT = 2

HERE = pathlib.Path(__file__).resolve().parent
CREDS = HERE / "edhoc_creds.json"


def build_credential_entry(creds):
    """Assemble the aiocoap 'edhoc-oscore' credentials dict from edhoc_creds.json.

    own_cred/peer_cred are {14: <CCS-dict>}; aiocoap re-encodes the CCS with
    canonical CBOR, matching the bytes baked into the device (edhoc_creds.h).
    private_key is the initiator COSE_Key {1:EC, -1:P-256, -4:d}.
    """
    ini = creds["initiator"]
    res = creds["responder"]

    own_cred = {14: cbor2.loads(bytes.fromhex(ini["ccs"]))}
    peer_cred = {14: cbor2.loads(bytes.fromhex(res["ccs"]))}
    private_key = {1: 2, -1: 1, -4: bytes.fromhex(ini["priv"])}

    return {
        "edhoc-oscore": {
            "suite": creds["suite"],
            "method": creds["method"],
            "own_cred_style": "by-key-id",
            "own_cred": own_cred,
            "private_key": private_key,
            "peer_cred": peer_cred,
            # Use the RFC 9668 *sequential* flow: send message_3 as its own POST
            # to /.well-known/edhoc and process the message_4 reply, rather than
            # aiocoap's default "combined" optimisation (message_3 folded into the
            # first OSCORE request). The device (src/edhoc_oscore.c) implements the
            # sequential responder + message_4; the combined request is not handled.
            "use_combined_edhoc": False,
        }
    }


async def run(host):
    creds = json.loads(CREDS.read_text())
    entry = build_credential_entry(creds)

    ctx = await aiocoap.Context.create_client_context()
    ctx.client_credentials.load_from_dict({f"coap://{host}/*": entry})

    # (code, path, payload). The first request triggers the EDHOC handshake.
    requests = [
        (aiocoap.GET, "hello", None),
        (aiocoap.GET, "led", None),
        (aiocoap.PUT, "led", b"1"),
        (aiocoap.GET, "led", None),
        (aiocoap.PUT, "led", b"0"),
    ]

    print(f"OSCORE client -> coap://{host} (EDHOC on first request)\n")
    ok = True
    for code, path, payload in requests:
        msg = aiocoap.Message(code=code, uri=f"coap://{host}/{path}")
        if payload is not None:
            msg.payload = payload
        label = f"{code.name} /{path}" + (f" = {payload!r}" if payload else "")
        try:
            # First request drives the whole EDHOC handshake, each message of
            # which is a slow software-P-256 round trip on the device (~4 s+).
            resp = await asyncio.wait_for(ctx.request(msg).response, timeout=30)
            body = resp.payload.decode("utf-8", "replace")
            print(f"  {label:20s} -> {resp.code}  {body!r}")
        except Exception as exc:  # noqa: BLE001 -- surface any failure to the user
            ok = False
            print(f"  {label:20s} -> ERROR: {exc!r}")

    await ctx.shutdown()
    if not ok:
        raise SystemExit(1)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--host", default="192.0.2.1")
    args = ap.parse_args()
    asyncio.run(run(args.host))


if __name__ == "__main__":
    main()
